# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:12
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170716_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='MarkDown 문법을 지원합니다.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='이름 3글자만 넣어주세요.', max_length=100, validators=[blog.models.min_length_3_validator]),
        ),
    ]
