# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/post/%Y/%m/%d'),
        ),
    ]
